baseURL = "/"
languageCode = "en-GB"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    title = "UK Web Archive Data Site"
    weight = 1
    languageName = "English"
  [languages.cy]
    title = "UK Web Archive Data Site Welsh"
    weight = 2
    languageName = "Welsh"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

canonifyURLs = true

[params]
  editURL = "https://github.com/ukwa/opendata/edit/master/content/"
  description = "Documentation Woo"
  author = "UKWA WWOO"
  showVisitedLinks = false
  themeVariant = "ukwa"

ignoreFiles = [ "\\.ad$" ]


# For search functionnality: JSON
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Additional formats to build DataCite files:
[mediaTypes]
  [mediaTypes."application/xml-datacite"]
  suffix = "xml"
  [mediaTypes."application/x-datacite-resolve"]
  suffix = "resolve"

[outputFormats]
  [outputFormats.DCXML]
  mediaType = "application/xml-datacite"
  baseName = "datacite"
  isPlainText = true
  [outputFormats.DCRESOLVE]
  mediaType = "application/x-datacite-resolve"
  baseName = "datacite"
  isPlainText = true

# The Menu
[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> UKWA Homepage"
identifier = "ukwa"
url = "https://www.webarchive.org.uk/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-twitter'></i> @UKWebArchive"
identifier = "ukwa-twitter"
url = "https://twitter.com/UKWebArchive"
weight = 30

[[menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ukwa/opendata"
weight = 10

